import Head from 'next/head'
import Image from 'next/image'
import { Special_Elite } from '@next/font/google'
// import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import styles from '@/styles/Home.module.css'


const SpecialElite = Special_Elite({ subsets: ['latin'], weight: ['400'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
       
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main id = "noBootsrap" className={`${styles.main} ${SpecialElite.className}`}>
        <div className={styles.homediv}>
          <p className={styles.hello}>Hello, my name is</p>
          <div>
            <h1 className={styles.name}>Paul Kim</h1> 
          </div>
          <p className={styles.hello}>and I'm a Software Engineer from Seattle, Washington</p>
        </div>
      </main>
    </>
  )
}
